[package]
name = "ownership-and-borrowing"
version = "0.1.0"
authors = ["suren <suren-m>"]
edition = "2018"
default-run = "main"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
